# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'improvisation2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1195, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.globalGridLayout = QtWidgets.QGridLayout()
        self.globalGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.globalGridLayout.setSpacing(0)
        self.globalGridLayout.setObjectName("globalGridLayout")
        self.globalVerticalLayout = QtWidgets.QVBoxLayout()
        self.globalVerticalLayout.setSpacing(40)
        self.globalVerticalLayout.setObjectName("globalVerticalLayout")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Titre.sizePolicy().hasHeightForWidth())
        self.Titre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Titre.setFont(font)
        self.Titre.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titre.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Titre.setScaledContents(False)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.globalVerticalLayout.addWidget(self.Titre)
        self.horizontalLayout_animation = QtWidgets.QHBoxLayout()
        self.horizontalLayout_animation.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_animation.setSpacing(0)
        self.horizontalLayout_animation.setObjectName("horizontalLayout_animation")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem)
        self.animationSubstrat = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationSubstrat.sizePolicy().hasHeightForWidth())
        self.animationSubstrat.setSizePolicy(sizePolicy)
        self.animationSubstrat.setMinimumSize(QtCore.QSize(300, 300))
        self.animationSubstrat.setMaximumSize(QtCore.QSize(400, 600))
        self.animationSubstrat.setStyleSheet("background-color: blue\n"
"")
        self.animationSubstrat.setObjectName("animationSubstrat")
        self.horizontalLayout_animation.addWidget(self.animationSubstrat)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem1)
        self.gridLayout_donnees = QtWidgets.QGridLayout()
        self.gridLayout_donnees.setObjectName("gridLayout_donnees")
        self.donnees_7 = QtWidgets.QHBoxLayout()
        self.donnees_7.setObjectName("donnees_7")
        self.temps = QtWidgets.QLabel(self.centralwidget)
        self.temps.setObjectName("temps")
        self.donnees_7.addWidget(self.temps)
        self.tempsVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.tempsVal.setObjectName("tempsVal")
        self.donnees_7.addWidget(self.tempsVal)
        self.gridLayout_donnees.addLayout(self.donnees_7, 6, 0, 1, 1)
        self.donnees_6 = QtWidgets.QHBoxLayout()
        self.donnees_6.setObjectName("donnees_6")
        self.vDiff = QtWidgets.QLabel(self.centralwidget)
        self.vDiff.setObjectName("vDiff")
        self.donnees_6.addWidget(self.vDiff)
        self.vDiffVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.vDiffVal.setObjectName("vDiffVal")
        self.donnees_6.addWidget(self.vDiffVal)
        self.gridLayout_donnees.addLayout(self.donnees_6, 5, 0, 1, 1)
        self.donnees_1 = QtWidgets.QHBoxLayout()
        self.donnees_1.setObjectName("donnees_1")
        self.largeur = QtWidgets.QLabel(self.centralwidget)
        self.largeur.setObjectName("largeur")
        self.donnees_1.addWidget(self.largeur)
        self.largeurVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.largeurVal.setObjectName("largeurVal")
        self.donnees_1.addWidget(self.largeurVal)
        self.gridLayout_donnees.addLayout(self.donnees_1, 0, 0, 1, 1)
        self.donnees_5 = QtWidgets.QHBoxLayout()
        self.donnees_5.setObjectName("donnees_5")
        self.cDiff = QtWidgets.QLabel(self.centralwidget)
        self.cDiff.setObjectName("cDiff")
        self.donnees_5.addWidget(self.cDiff)
        self.cDiffVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cDiffVal.setObjectName("cDiffVal")
        self.donnees_5.addWidget(self.cDiffVal)
        self.gridLayout_donnees.addLayout(self.donnees_5, 4, 0, 1, 1)
        self.donnees_2 = QtWidgets.QHBoxLayout()
        self.donnees_2.setObjectName("donnees_2")
        self.nbCases = QtWidgets.QLabel(self.centralwidget)
        self.nbCases.setObjectName("nbCases")
        self.donnees_2.addWidget(self.nbCases)
        self.nbCasesVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.nbCasesVal.setObjectName("nbCasesVal")
        self.donnees_2.addWidget(self.nbCasesVal)
        self.gridLayout_donnees.addLayout(self.donnees_2, 1, 0, 1, 1)
        self.donnees_4 = QtWidgets.QHBoxLayout()
        self.donnees_4.setObjectName("donnees_4")
        self.cIni = QtWidgets.QLabel(self.centralwidget)
        self.cIni.setObjectName("cIni")
        self.donnees_4.addWidget(self.cIni)
        self.cIniVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.cIniVal.setObjectName("cIniVal")
        self.donnees_4.addWidget(self.cIniVal)
        self.gridLayout_donnees.addLayout(self.donnees_4, 3, 0, 1, 1)
        self.donnees_3 = QtWidgets.QHBoxLayout()
        self.donnees_3.setObjectName("donnees_3")
        self.rayon = QtWidgets.QLabel(self.centralwidget)
        self.rayon.setObjectName("rayon")
        self.donnees_3.addWidget(self.rayon)
        self.rayonVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.rayonVal.setObjectName("rayonVal")
        self.donnees_3.addWidget(self.rayonVal)
        self.gridLayout_donnees.addLayout(self.donnees_3, 2, 0, 1, 1)
        self.donnees_8 = QtWidgets.QHBoxLayout()
        self.donnees_8.setObjectName("donnees_8")
        self.gdDelta = QtWidgets.QLabel(self.centralwidget)
        self.gdDelta.setObjectName("gdDelta")
        self.donnees_8.addWidget(self.gdDelta)
        self.gdDeltaVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.gdDeltaVal.setObjectName("gdDeltaVal")
        self.donnees_8.addWidget(self.gdDeltaVal)
        self.gridLayout_donnees.addLayout(self.donnees_8, 7, 0, 1, 1)
        self.entreeDonnee = QtWidgets.QHBoxLayout()
        self.entreeDonnee.setObjectName("entreeDonnee")
        self.entree = QtWidgets.QPushButton(self.centralwidget)
        self.entree.setMaximumSize(QtCore.QSize(100, 16777215))
        self.entree.setObjectName("entree")
        self.entreeDonnee.addWidget(self.entree)
        self.gridLayout_donnees.addLayout(self.entreeDonnee, 9, 0, 1, 1)
        self.donnees_9 = QtWidgets.QHBoxLayout()
        self.donnees_9.setObjectName("donnees_9")
        self.ptDelta = QtWidgets.QLabel(self.centralwidget)
        self.ptDelta.setObjectName("ptDelta")
        self.donnees_9.addWidget(self.ptDelta)
        self.ptDeltaVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ptDeltaVal.setObjectName("ptDeltaVal")
        self.donnees_9.addWidget(self.ptDeltaVal)
        self.gridLayout_donnees.addLayout(self.donnees_9, 8, 0, 1, 1)
        self.horizontalLayout_animation.addLayout(self.gridLayout_donnees)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem2)
        self.horizontalLayout_animation.setStretch(1, 2)
        self.globalVerticalLayout.addLayout(self.horizontalLayout_animation)
        self.verticalLayout_graphs = QtWidgets.QVBoxLayout()
        self.verticalLayout_graphs.setSpacing(0)
        self.verticalLayout_graphs.setObjectName("verticalLayout_graphs")
        self.horizontalLayout_forLabel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_forLabel.setObjectName("horizontalLayout_forLabel")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem3)
        self.titreGraph_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titreGraph_1.sizePolicy().hasHeightForWidth())
        self.titreGraph_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titreGraph_1.setFont(font)
        self.titreGraph_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titreGraph_1.setAlignment(QtCore.Qt.AlignCenter)
        self.titreGraph_1.setObjectName("titreGraph_1")
        self.horizontalLayout_forLabel.addWidget(self.titreGraph_1)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem4)
        self.titreGraph_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titreGraph_2.sizePolicy().hasHeightForWidth())
        self.titreGraph_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titreGraph_2.setFont(font)
        self.titreGraph_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titreGraph_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titreGraph_2.setObjectName("titreGraph_2")
        self.horizontalLayout_forLabel.addWidget(self.titreGraph_2)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem5)
        self.verticalLayout_graphs.addLayout(self.horizontalLayout_forLabel)
        self.horizontalLayout_forGraphs = QtWidgets.QHBoxLayout()
        self.horizontalLayout_forGraphs.setObjectName("horizontalLayout_forGraphs")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem6)
        self.graph_1 = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_1.sizePolicy().hasHeightForWidth())
        self.graph_1.setSizePolicy(sizePolicy)
        self.graph_1.setMinimumSize(QtCore.QSize(500, 300))
        self.graph_1.setMaximumSize(QtCore.QSize(600, 300))
        self.graph_1.setStyleSheet("background-color: green")
        self.graph_1.setObjectName("graph_1")
        self.horizontalLayout_forGraphs.addWidget(self.graph_1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem7)
        self.graph_2 = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_2.sizePolicy().hasHeightForWidth())
        self.graph_2.setSizePolicy(sizePolicy)
        self.graph_2.setMinimumSize(QtCore.QSize(500, 300))
        self.graph_2.setMaximumSize(QtCore.QSize(600, 300))
        self.graph_2.setStyleSheet("background-color: yellow")
        self.graph_2.setObjectName("graph_2")
        self.horizontalLayout_forGraphs.addWidget(self.graph_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem8)
        self.verticalLayout_graphs.addLayout(self.horizontalLayout_forGraphs)
        self.globalVerticalLayout.addLayout(self.verticalLayout_graphs)
        self.globalGridLayout.addLayout(self.globalVerticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.globalGridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1195, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.entree.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titre.setText(_translate("MainWindow", "Cellulose 21"))
        self.temps.setText(_translate("MainWindow", "Temps de simulation (en h) = "))
        self.vDiff.setText(_translate("MainWindow", "Vitesse de diffusion (en µm²/h) =  "))
        self.largeur.setText(_translate("MainWindow", "Largeur (µm) = "))
        self.cDiff.setText(_translate("MainWindow", "Concentration pour diffuser (en pg/µ²) = "))
        self.nbCases.setText(_translate("MainWindow", "Nombre de cases = "))
        self.cIni.setText(_translate("MainWindow", "Concentration initiale (en pg/µ²) = "))
        self.rayon.setText(_translate("MainWindow", "Rayon du cercle (en µm) = "))
        self.gdDelta.setText(_translate("MainWindow", "Delta = "))
        self.entree.setText(_translate("MainWindow", "Entrée"))
        self.ptDelta.setText(_translate("MainWindow", "delta = "))
        self.titreGraph_1.setText(_translate("MainWindow", "Insérer le texte correspondant au graphe"))
        self.titreGraph_2.setText(_translate("MainWindow", "Insérer le texte correspondant au graphe"))

from mplwidget import Mplwidget
