# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Simulation.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from mplwidget import Mplwidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1279, 919)
        MainWindow.setStyleSheet("background-color: rgb(183, 207, 208)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.globalGridLayout = QtWidgets.QGridLayout()
        self.globalGridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.globalGridLayout.setSpacing(0)
        self.globalGridLayout.setObjectName("globalGridLayout")
        self.globalVerticalLayout = QtWidgets.QVBoxLayout()
        self.globalVerticalLayout.setSpacing(40)
        self.globalVerticalLayout.setObjectName("globalVerticalLayout")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Titre.sizePolicy().hasHeightForWidth())
        self.Titre.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Titre.setFont(font)
        self.Titre.setStyleSheet("font: 75 20pt \"Century Schoolbook L\";")
        self.Titre.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titre.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Titre.setScaledContents(False)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.globalVerticalLayout.addWidget(self.Titre)
        self.horizontalLayout_animation = QtWidgets.QHBoxLayout()
        self.horizontalLayout_animation.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_animation.setSpacing(1)
        self.horizontalLayout_animation.setObjectName("horizontalLayout_animation")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.animationSubstrat = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationSubstrat.sizePolicy().hasHeightForWidth())
        self.animationSubstrat.setSizePolicy(sizePolicy)
        self.animationSubstrat.setMinimumSize(QtCore.QSize(400, 400))
        self.animationSubstrat.setMaximumSize(QtCore.QSize(400, 400))
        self.animationSubstrat.setStyleSheet("background-color: blue\n"
"")
        self.animationSubstrat.setObjectName("animationSubstrat")
        self.verticalLayout_4.addWidget(self.animationSubstrat)
        self.horizontalLayout_animation.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setStyleSheet("background-color : white")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_donnees = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_donnees.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_donnees.setSpacing(5)
        self.gridLayout_donnees.setObjectName("gridLayout_donnees")
        self.nbCasesVal = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbCasesVal.sizePolicy().hasHeightForWidth())
        self.nbCasesVal.setSizePolicy(sizePolicy)
        self.nbCasesVal.setMinimumSize(QtCore.QSize(30, 0))
        self.nbCasesVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.nbCasesVal.setMaximum(999)
        self.nbCasesVal.setProperty("value", 250)
        self.nbCasesVal.setObjectName("nbCasesVal")
        self.gridLayout_donnees.addWidget(self.nbCasesVal, 1, 2, 1, 1)
        self.cIniVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cIniVal.sizePolicy().hasHeightForWidth())
        self.cIniVal.setSizePolicy(sizePolicy)
        self.cIniVal.setMinimumSize(QtCore.QSize(30, 0))
        self.cIniVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.cIniVal.setMaximum(999.0)
        self.cIniVal.setSingleStep(0.01)
        self.cIniVal.setProperty("value", 0.4)
        self.cIniVal.setObjectName("cIniVal")
        self.gridLayout_donnees.addWidget(self.cIniVal, 3, 2, 1, 1)
        self.rayonVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rayonVal.sizePolicy().hasHeightForWidth())
        self.rayonVal.setSizePolicy(sizePolicy)
        self.rayonVal.setMinimumSize(QtCore.QSize(30, 0))
        self.rayonVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.rayonVal.setMaximum(999.0)
        self.rayonVal.setSingleStep(0.01)
        self.rayonVal.setProperty("value", 25.0)
        self.rayonVal.setObjectName("rayonVal")
        self.gridLayout_donnees.addWidget(self.rayonVal, 2, 2, 1, 1)
        self.vDiffVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vDiffVal.sizePolicy().hasHeightForWidth())
        self.vDiffVal.setSizePolicy(sizePolicy)
        self.vDiffVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.vDiffVal.setMaximum(999.0)
        self.vDiffVal.setSingleStep(0.01)
        self.vDiffVal.setProperty("value", 5.0)
        self.vDiffVal.setObjectName("vDiffVal")
        self.gridLayout_donnees.addWidget(self.vDiffVal, 5, 2, 1, 1)
        self.cDiffVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cDiffVal.sizePolicy().hasHeightForWidth())
        self.cDiffVal.setSizePolicy(sizePolicy)
        self.cDiffVal.setMinimumSize(QtCore.QSize(30, 0))
        self.cDiffVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.cDiffVal.setMaximum(999.0)
        self.cDiffVal.setSingleStep(0.01)
        self.cDiffVal.setProperty("value", 0.3)
        self.cDiffVal.setObjectName("cDiffVal")
        self.gridLayout_donnees.addWidget(self.cDiffVal, 4, 2, 1, 1)
        self.tempsVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempsVal.sizePolicy().hasHeightForWidth())
        self.tempsVal.setSizePolicy(sizePolicy)
        self.tempsVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.tempsVal.setMaximum(999.0)
        self.tempsVal.setSingleStep(0.01)
        self.tempsVal.setProperty("value", 30.0)
        self.tempsVal.setObjectName("tempsVal")
        self.gridLayout_donnees.addWidget(self.tempsVal, 6, 2, 1, 1)
        self.gdDeltaVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdDeltaVal.sizePolicy().hasHeightForWidth())
        self.gdDeltaVal.setSizePolicy(sizePolicy)
        self.gdDeltaVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.gdDeltaVal.setDecimals(2)
        self.gdDeltaVal.setMaximum(999.0)
        self.gdDeltaVal.setSingleStep(0.01)
        self.gdDeltaVal.setProperty("value", 0.3)
        self.gdDeltaVal.setObjectName("gdDeltaVal")
        self.gridLayout_donnees.addWidget(self.gdDeltaVal, 7, 2, 1, 1)
        self.ptDeltaVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ptDeltaVal.sizePolicy().hasHeightForWidth())
        self.ptDeltaVal.setSizePolicy(sizePolicy)
        self.ptDeltaVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";\n"
"")
        self.ptDeltaVal.setDecimals(3)
        self.ptDeltaVal.setMaximum(999.0)
        self.ptDeltaVal.setSingleStep(0.01)
        self.ptDeltaVal.setProperty("value", 0.005)
        self.ptDeltaVal.setObjectName("ptDeltaVal")
        self.gridLayout_donnees.addWidget(self.ptDeltaVal, 8, 2, 1, 1)
        self.longueurVal = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.longueurVal.sizePolicy().hasHeightForWidth())
        self.longueurVal.setSizePolicy(sizePolicy)
        self.longueurVal.setMinimumSize(QtCore.QSize(30, 0))
        self.longueurVal.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.longueurVal.setMaximum(999.0)
        self.longueurVal.setSingleStep(0.01)
        self.longueurVal.setProperty("value", 80.0)
        self.longueurVal.setObjectName("longueurVal")
        self.gridLayout_donnees.addWidget(self.longueurVal, 0, 2, 1, 1)
        self.ptDelta = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ptDelta.sizePolicy().hasHeightForWidth())
        self.ptDelta.setSizePolicy(sizePolicy)
        self.ptDelta.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.ptDelta.setObjectName("ptDelta")
        self.gridLayout_donnees.addWidget(self.ptDelta, 8, 1, 1, 1)
        self.vDiff = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vDiff.sizePolicy().hasHeightForWidth())
        self.vDiff.setSizePolicy(sizePolicy)
        self.vDiff.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.vDiff.setObjectName("vDiff")
        self.gridLayout_donnees.addWidget(self.vDiff, 5, 1, 1, 1)
        self.gdDelta = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gdDelta.sizePolicy().hasHeightForWidth())
        self.gdDelta.setSizePolicy(sizePolicy)
        self.gdDelta.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.gdDelta.setObjectName("gdDelta")
        self.gridLayout_donnees.addWidget(self.gdDelta, 7, 1, 1, 1)
        self.temps = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temps.sizePolicy().hasHeightForWidth())
        self.temps.setSizePolicy(sizePolicy)
        self.temps.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.temps.setObjectName("temps")
        self.gridLayout_donnees.addWidget(self.temps, 6, 1, 1, 1)
        self.masse_ini = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masse_ini.sizePolicy().hasHeightForWidth())
        self.masse_ini.setSizePolicy(sizePolicy)
        self.masse_ini.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.masse_ini.setObjectName("masse_ini")
        self.gridLayout_donnees.addWidget(self.masse_ini, 0, 3, 1, 1)
        self.v_deplacement_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_deplacement_val.sizePolicy().hasHeightForWidth())
        self.v_deplacement_val.setSizePolicy(sizePolicy)
        self.v_deplacement_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.v_deplacement_val.setMaximum(999.0)
        self.v_deplacement_val.setSingleStep(0.1)
        self.v_deplacement_val.setProperty("value", 0.1)
        self.v_deplacement_val.setObjectName("v_deplacement_val")
        self.gridLayout_donnees.addWidget(self.v_deplacement_val, 2, 4, 1, 1)
        self.vmax_bacterie_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmax_bacterie_val.sizePolicy().hasHeightForWidth())
        self.vmax_bacterie_val.setSizePolicy(sizePolicy)
        self.vmax_bacterie_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.vmax_bacterie_val.setMaximum(999.0)
        self.vmax_bacterie_val.setSingleStep(0.1)
        self.vmax_bacterie_val.setProperty("value", 10.0)
        self.vmax_bacterie_val.setObjectName("vmax_bacterie_val")
        self.gridLayout_donnees.addWidget(self.vmax_bacterie_val, 3, 4, 1, 1)
        self.v_absorb_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_absorb_val.sizePolicy().hasHeightForWidth())
        self.v_absorb_val.setSizePolicy(sizePolicy)
        self.v_absorb_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.v_absorb_val.setMaximum(999.0)
        self.v_absorb_val.setSingleStep(0.1)
        self.v_absorb_val.setProperty("value", 0.1)
        self.v_absorb_val.setObjectName("v_absorb_val")
        self.gridLayout_donnees.addWidget(self.v_absorb_val, 1, 4, 1, 1)
        self.v_absorb = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_absorb.sizePolicy().hasHeightForWidth())
        self.v_absorb.setSizePolicy(sizePolicy)
        self.v_absorb.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.v_absorb.setObjectName("v_absorb")
        self.gridLayout_donnees.addWidget(self.v_absorb, 1, 3, 1, 1)
        self.k_conv_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k_conv_val.sizePolicy().hasHeightForWidth())
        self.k_conv_val.setSizePolicy(sizePolicy)
        self.k_conv_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.k_conv_val.setMaximum(999.0)
        self.k_conv_val.setSingleStep(0.1)
        self.k_conv_val.setProperty("value", 0.2)
        self.k_conv_val.setObjectName("k_conv_val")
        self.gridLayout_donnees.addWidget(self.k_conv_val, 4, 4, 1, 1)
        self.v_deplacement = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_deplacement.sizePolicy().hasHeightForWidth())
        self.v_deplacement.setSizePolicy(sizePolicy)
        self.v_deplacement.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.v_deplacement.setObjectName("v_deplacement")
        self.gridLayout_donnees.addWidget(self.v_deplacement, 2, 3, 1, 1)
        self.masse_ini_val = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masse_ini_val.sizePolicy().hasHeightForWidth())
        self.masse_ini_val.setSizePolicy(sizePolicy)
        self.masse_ini_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.masse_ini_val.setMaximum(999.0)
        self.masse_ini_val.setSingleStep(0.1)
        self.masse_ini_val.setProperty("value", 0.4)
        self.masse_ini_val.setObjectName("masse_ini_val")
        self.gridLayout_donnees.addWidget(self.masse_ini_val, 0, 4, 1, 1)
        self.nb_bacterie = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nb_bacterie.sizePolicy().hasHeightForWidth())
        self.nb_bacterie.setSizePolicy(sizePolicy)
        self.nb_bacterie.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.nb_bacterie.setObjectName("nb_bacterie")
        self.gridLayout_donnees.addWidget(self.nb_bacterie, 5, 3, 1, 1)
        self.k_conv = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.k_conv.sizePolicy().hasHeightForWidth())
        self.k_conv.setSizePolicy(sizePolicy)
        self.k_conv.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.k_conv.setObjectName("k_conv")
        self.gridLayout_donnees.addWidget(self.k_conv, 4, 3, 1, 1)
        self.vmax_bacterie = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vmax_bacterie.sizePolicy().hasHeightForWidth())
        self.vmax_bacterie.setSizePolicy(sizePolicy)
        self.vmax_bacterie.setStyleSheet("\n"
"\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.vmax_bacterie.setObjectName("vmax_bacterie")
        self.gridLayout_donnees.addWidget(self.vmax_bacterie, 3, 3, 1, 1)
        self.nb_bacterie_val = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nb_bacterie_val.sizePolicy().hasHeightForWidth())
        self.nb_bacterie_val.setSizePolicy(sizePolicy)
        self.nb_bacterie_val.setStyleSheet("background-color: white;\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.nb_bacterie_val.setMaximum(999)
        self.nb_bacterie_val.setProperty("value", 50)
        self.nb_bacterie_val.setObjectName("nb_bacterie_val")
        self.gridLayout_donnees.addWidget(self.nb_bacterie_val, 5, 4, 1, 1)
        self.largeur = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.largeur.sizePolicy().hasHeightForWidth())
        self.largeur.setSizePolicy(sizePolicy)
        self.largeur.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.largeur.setObjectName("largeur")
        self.gridLayout_donnees.addWidget(self.largeur, 0, 1, 1, 1)
        self.cDiff = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cDiff.sizePolicy().hasHeightForWidth())
        self.cDiff.setSizePolicy(sizePolicy)
        self.cDiff.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.cDiff.setObjectName("cDiff")
        self.gridLayout_donnees.addWidget(self.cDiff, 4, 1, 1, 1)
        self.cIni = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cIni.sizePolicy().hasHeightForWidth())
        self.cIni.setSizePolicy(sizePolicy)
        self.cIni.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.cIni.setObjectName("cIni")
        self.gridLayout_donnees.addWidget(self.cIni, 3, 1, 1, 1)
        self.nbCasesVal_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nbCasesVal_2.sizePolicy().hasHeightForWidth())
        self.nbCasesVal_2.setSizePolicy(sizePolicy)
        self.nbCasesVal_2.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.nbCasesVal_2.setObjectName("nbCasesVal_2")
        self.gridLayout_donnees.addWidget(self.nbCasesVal_2, 1, 1, 1, 1)
        self.rayon = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rayon.sizePolicy().hasHeightForWidth())
        self.rayon.setSizePolicy(sizePolicy)
        self.rayon.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.rayon.setObjectName("rayon")
        self.gridLayout_donnees.addWidget(self.rayon, 2, 1, 1, 1)
        self.nameFileBox = QtWidgets.QPlainTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameFileBox.sizePolicy().hasHeightForWidth())
        self.nameFileBox.setSizePolicy(sizePolicy)
        self.nameFileBox.setMaximumSize(QtCore.QSize(200, 30))
        self.nameFileBox.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.nameFileBox.setObjectName("nameFileBox")
        self.gridLayout_donnees.addWidget(self.nameFileBox, 9, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("\n"
"font: 75 10pt \"Century Schoolbook L\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_donnees.addWidget(self.label_2, 9, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadJSON = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadJSON.sizePolicy().hasHeightForWidth())
        self.loadJSON.setSizePolicy(sizePolicy)
        self.loadJSON.setStyleSheet("background-color: white;\n"
"\n"
"")
        self.loadJSON.setObjectName("loadJSON")
        self.horizontalLayout_2.addWidget(self.loadJSON)
        self.saveToJSON = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveToJSON.sizePolicy().hasHeightForWidth())
        self.saveToJSON.setSizePolicy(sizePolicy)
        self.saveToJSON.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.saveToJSON.setObjectName("saveToJSON")
        self.horizontalLayout_2.addWidget(self.saveToJSON)
        self.gridLayout_donnees.addLayout(self.horizontalLayout_2, 10, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.entreeDonnee = QtWidgets.QHBoxLayout()
        self.entreeDonnee.setObjectName("entreeDonnee")
        self.entree = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entree.sizePolicy().hasHeightForWidth())
        self.entree.setSizePolicy(sizePolicy)
        self.entree.setMinimumSize(QtCore.QSize(0, 0))
        self.entree.setMaximumSize(QtCore.QSize(100, 16777215))
        self.entree.setStyleSheet("background-color: white;")
        self.entree.setObjectName("entree")
        self.entreeDonnee.addWidget(self.entree)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start.sizePolicy().hasHeightForWidth())
        self.start.setSizePolicy(sizePolicy)
        self.start.setStyleSheet("background-color: white;")
        self.start.setObjectName("start")
        self.entreeDonnee.addWidget(self.start)
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setStyleSheet("background-color: white;")
        self.stop.setObjectName("stop")
        self.entreeDonnee.addWidget(self.stop)
        self.gridLayout_4.addLayout(self.entreeDonnee, 1, 0, 1, 1)
        self.horizontalLayout_animation.addLayout(self.gridLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_animation.addItem(spacerItem2)
        self.globalVerticalLayout.addLayout(self.horizontalLayout_animation)
        self.verticalLayout_graphs = QtWidgets.QVBoxLayout()
        self.verticalLayout_graphs.setSpacing(0)
        self.verticalLayout_graphs.setObjectName("verticalLayout_graphs")
        self.horizontalLayout_forLabel = QtWidgets.QHBoxLayout()
        self.horizontalLayout_forLabel.setObjectName("horizontalLayout_forLabel")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem3)
        self.titreGraph_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titreGraph_1.sizePolicy().hasHeightForWidth())
        self.titreGraph_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.titreGraph_1.setFont(font)
        self.titreGraph_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titreGraph_1.setStyleSheet("font: 75 10pt \"Century Schoolbook L\";")
        self.titreGraph_1.setAlignment(QtCore.Qt.AlignCenter)
        self.titreGraph_1.setObjectName("titreGraph_1")
        self.horizontalLayout_forLabel.addWidget(self.titreGraph_1)
        spacerItem4 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem4)
        self.titreGraph_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titreGraph_2.sizePolicy().hasHeightForWidth())
        self.titreGraph_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.titreGraph_2.setFont(font)
        self.titreGraph_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titreGraph_2.setStyleSheet("font: 75 10pt \"Century Schoolbook L\";")
        self.titreGraph_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titreGraph_2.setObjectName("titreGraph_2")
        self.horizontalLayout_forLabel.addWidget(self.titreGraph_2)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forLabel.addItem(spacerItem5)
        self.verticalLayout_graphs.addLayout(self.horizontalLayout_forLabel)
        self.horizontalLayout_forGraphs = QtWidgets.QHBoxLayout()
        self.horizontalLayout_forGraphs.setObjectName("horizontalLayout_forGraphs")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem6)
        self.graph_1 = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_1.sizePolicy().hasHeightForWidth())
        self.graph_1.setSizePolicy(sizePolicy)
        self.graph_1.setMinimumSize(QtCore.QSize(500, 300))
        self.graph_1.setMaximumSize(QtCore.QSize(600, 300))
        self.graph_1.setStyleSheet("background-color: green")
        self.graph_1.setObjectName("graph_1")
        self.horizontalLayout_forGraphs.addWidget(self.graph_1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem7)
        self.graph_2 = Mplwidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_2.sizePolicy().hasHeightForWidth())
        self.graph_2.setSizePolicy(sizePolicy)
        self.graph_2.setMinimumSize(QtCore.QSize(500, 300))
        self.graph_2.setMaximumSize(QtCore.QSize(600, 300))
        self.graph_2.setStyleSheet("background-color: yellow")
        self.graph_2.setObjectName("graph_2")
        self.horizontalLayout_forGraphs.addWidget(self.graph_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_forGraphs.addItem(spacerItem8)
        self.verticalLayout_graphs.addLayout(self.horizontalLayout_forGraphs)
        self.globalVerticalLayout.addLayout(self.verticalLayout_graphs)
        self.globalGridLayout.addLayout(self.globalVerticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.globalGridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1279, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.entree.clicked.connect(MainWindow.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titre.setText(_translate("MainWindow", "Cellulose 21"))
        self.label.setText(_translate("MainWindow", " Concentration de cellulose avec bactéries"))
        self.ptDeltaVal.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>background-color: white;</p></body></html>"))
        self.ptDelta.setText(_translate("MainWindow", "delta = "))
        self.vDiff.setText(_translate("MainWindow", "Vitesse de diffusion (en µm²/h) =  "))
        self.gdDelta.setText(_translate("MainWindow", "Delta = "))
        self.temps.setText(_translate("MainWindow", "Temps de simulation (en h) = "))
        self.masse_ini.setText(_translate("MainWindow", "Masse initiale des bactérie (pg) ="))
        self.v_absorb.setText(_translate("MainWindow", "Vitesse d\'absorbtion (µm/h) ="))
        self.v_deplacement.setText(_translate("MainWindow", "Vitesse déplacement (µm^4)/(pg h) ="))
        self.nb_bacterie.setText(_translate("MainWindow", "Nombre bactérie initiale ="))
        self.k_conv.setText(_translate("MainWindow", "Constante de conversion masse/biomasse ="))
        self.vmax_bacterie.setText(_translate("MainWindow", "Vitesse max des bactérie (µm/h) ="))
        self.largeur.setText(_translate("MainWindow", "Longueur (µm) = "))
        self.cDiff.setText(_translate("MainWindow", "Concentration pour diffuser (en pg/µ²) = "))
        self.cIni.setText(_translate("MainWindow", "Concentration initiale (en pg/µ²) = "))
        self.nbCasesVal_2.setText(_translate("MainWindow", "Nombre de cases = "))
        self.rayon.setText(_translate("MainWindow", "Rayon du cercle (en µm) = "))
        self.label_2.setText(_translate("MainWindow", "Nom du fichier :"))
        self.loadJSON.setText(_translate("MainWindow", "Charger"))
        self.saveToJSON.setText(_translate("MainWindow", "Enregistrer"))
        self.entree.setText(_translate("MainWindow", "Lancer"))
        self.start.setText(_translate("MainWindow", "Continuer"))
        self.stop.setText(_translate("MainWindow", "Pause"))
        self.titreGraph_1.setText(_translate("MainWindow", "Concentration du substrat"))
        self.titreGraph_2.setText(_translate("MainWindow", "Population de bactéries"))
